// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env file
dotenv.config();

const dbUrl = process.env.DATABASE_URL || "postgresql://bodyndry:bodyndry_secret@localhost:5432/bodyndry";
console.log("Using DATABASE_URL:", dbUrl);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
